### ISSUE TITLE
Unable to pull/push from/to GitHub repo after upgrading from 0.5.8 to 0.7.0 

### ISSUE THREAD

**Issue by laxmiatwork** [desktop/desktop#2377]
### Description

I am unable to pull after upgrading to 0.7.0 or 0.7.2. I am getting the following error. fatal: 

"unable to access 'https://github.com/[our_repo].git/': Failed to connect to github.com port 443: Bad access"

If I uninstall and install 0.5.8(from prior download) then I am able to push/pull from GitHub. But as soon as I restart GitHub automatically upgrades to a newer version. The upgraded version fails to pull/push from GitHub repo.
### Version

**GitHub Desktop version:** 0.7.0

**OS version:** Microsoft Windows [Version 10.0.10240]

### Steps to Reproduce

1. Install 0.5.8 - Verify that push/pull from a GitHub repo works
2. Restart GitHub for windows client. Verify that GitHub for Windows it was automatically upgraded. Test push/pull from GitHub repo. It fails.

**Expected behavior:** Successfully pull/push from GitHub.

**Actual behavior:** Pull/push fails with the following error.
unable to access 'https://github.com/[our_repo].git/': Failed to connect to github.com port 443: Bad access

**Reproduces how often:** 100%

### Logs
2017-08-01T01:40:36.220Z - error: Uncaught exception on main process
Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\lnarukonda\AppData\Local\GitHubDesktop\app-0.5.8\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as screen] (C:\Users\lnarukonda\AppData\Local\GitHubDesktop\app-0.5.8\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at o.exports (C:\Users\lnarukonda\AppData\Local\GitHubDesktop\app-0.5.8\resources\app\main.js:12:10094)
    at new L (C:\Users\lnarukonda\AppData\Local\GitHubDesktop\app-0.5.8\resources\app\main.js:1:37614)
    at g (C:\Users\lnarukonda\AppData\Local\GitHubDesktop\app-0.5.8\resources\app\main.js:14:79610)
    at App.S.app.on (C:\Users\lnarukonda\AppData\Local\GitHubDesktop\app-0.5.8\resources\app\main.js:14:80984)
2017-08-01T04:12:05.397Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to fetch
2017-08-01T04:12:05.400Z - warn: [ui] fetchCommit: returned an error 'fatface/IntegrationHub@78d5227b6092f292d3b6329d36204e1ce602c7cb'
TypeError: Failed to fetch
2017-08-01T04:12:05.400Z - warn: [ui] fetchIssues: failed for repository fatface/IntegrationHub
TypeError: Failed to fetch
2017-08-01T04:12:05.400Z - warn: [ui] Unable to fetch issues for fatface/IntegrationHub
TypeError: Failed to fetch
2017-08-01T04:12:05.417Z - warn: [ui] searchForUserWithEmail: not found 'kishan.soni@int.whishworks.com'
TypeError: Failed to fetch
2017-08-01T04:12:05.599Z - warn: [ui] fetchMentionables: failed for fatface/IntegrationHub
TypeError: Failed to fetch
2017-08-01T04:12:05.844Z - warn: [ui] fetchRepository: an error occurred for 'FatFace/IntegrationHub'
TypeError: Failed to fetch
2017-08-01T04:12:16.842Z - warn: [ui] getFetchPollInterval: failed for fatface/IntegrationHub
TypeError: Failed to fetch
2017-08-01T04:14:38.518Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 150.505s)
2017-08-01T04:14:38.521Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/FatFace/IntegrationHub.git/': Failed to connect to github.com port 443: Bad access

**Comment by joshaber** [comment]
Sorry for the delay! This looks really odd.

Could you go to Options > Accounts and make sure you're logged in?

**Comment by laxmiatwork** [comment]
It got resolved itself. I am not sure how. But I did not make any changes to my machine. I hope the logs I have provided will help you root cause the problem. At present, it not reproducible. So this issue can be closed. I will reopen or log a new one when I run into the problem again.

thank you

**Comment by shersial** [comment]
fatal: unable to access 'https://github.com/shersial/gulf-translate-ng.git/': Failed to connect to websenseproxy.sedd.gov.ae port 1080: Connection refused

but my port is 8080 I can pull from this repository but not push
