### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2647]
Sorry if I've missed this somewhere, but I've been trying to find instructions for building the app from the codebase on OS X but can't seem to locate any info.

Have tried cloning the repo and wanted to play around with the `build` and `compile` scripts there are, but not having success installing the dependencies, with npm failing at the `compile:tslint script.`. It throws a whole lot of similar errors related to TS:

```
node_modules/@types/react-virtualized/node_modules/@types/react/index.d.ts(3629,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'switch' must be of type 'SVGProps<SVGSwitchElement>', but here has type 'SVGProps<SVGSwitchElement>'.
```

Are there any official build instructions floating around somewhere or could someone point out what I'm missing? 

I have no problem building Atom on my environment, which is also an Electron app.

**Comment by lee-dohm** [comment]
The instructions are in the [documentation folder](https://github.com/desktop/desktop/tree/master/docs) in the [Development Environment Setup doc](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md), though yes, the links to get there could be more prominent or clearer.

Let us know if that doc doesn't answer your questions!

**Comment by adamreisnz** [comment]
Awesome thanks!

**Comment by adamreisnz** [comment]
Before I start digging in, will it build on Node 8 or would I need to downgrade to 7?

**Comment by lee-dohm** [comment]
I don't know if it will build on Node 8, I haven't tested it. (Personally, I use [nodenv](https://github.com/nodenv/nodenv) so that I don't have to downgrade, each project can use the exact right version of Node.)

**Comment by adamreisnz** [comment]
It looks like the problem I had was due to using yarn, using plain good 'ol `npm install` did the trick.

**Comment by adamreisnz** [comment]
Builds well on Node 8.4 👍
